# Generated by Django 2.1.4 on 2018-12-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsnap_rules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disaster',
            old_name='is_residency_required',
            new_name='residency_required',
        ),
    ]
