# Generated by Django 2.1.7 on 2019-03-06 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dsnap_rules', '0003_auto_20190221_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationperiod',
            name='registration_begin_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationperiod',
            name='registration_end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
