# Generated by Django 2.1.7 on 2019-03-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsnap_rules', '0004_auto_20190306_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
